name: Poll Stock Prices

on:
  schedule:
    - cron: '*/5 * * * *' # Run every 5 minutes for better reliability
  workflow_dispatch: # Allow manual trigger

jobs:
  poll:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Price Polling API
        run: curl -f -s -v -X GET "https://crawlstock.vercel.app/api/cron/poll-prices" -H "x-cron-secret:${{ secrets.CRON_SECRET }}"
